# Generated by Django 5.2.8 on 2025-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('PROCESSING', 'PROCESSING'), ('TRANSIT', 'TRANSIT'), ('READY_FOR_DELIVERY', 'READY FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='ORDERED', max_length=20),
        ),
    ]
